<?php
session_start();
if(isset($_POST['logout'])){
if(isset($_SESSION['loginAdminSessionGet']))
{
unset($_SESSION['loginAdminSessionGet']);
}
}
if(isset($_POST['logout1'])){
if(isset($_SESSION['loginSchoolSessionPost']))
{
unset($_SESSION['loginSchoolSessionPost']);
unset($_SESSION['loginSchoolSessionPostrandomdb']);	
}
}
if(isset($_POST['logout2'])){
if(isset($_SESSION['TeacherloginSchoolSessionPost'])){
unset($_SESSION['TeacherloginSchoolSessionPost']);
unset($_SESSION['TeacherloginSchoolSessionPostrandomdb']);	
}
}
if(isset($_POST['logout3'])){
if(isset($_SESSION['ParentloginSchoolSessionPost'])){
unset($_SESSION['ParentloginSchoolSessionPost']);
unset($_SESSION['ParentloginSchoolSessionPostrandomdb']);	
}
}
if(isset($_POST['logout4'])){
if(isset($_SESSION['StudentloginSchoolSessionPost'])){
unset($_SESSION['StudentloginSchoolSessionPost']);
unset($_SESSION['StudentloginSchoolSessionPostrandomdb']);	
}
}
?>
<script> window.location = '/login' </script>